require 'rails_helper'
require 'rack/test'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RemediationsController, type: :controller do
  login_admin

  let(:remediation) { create :remediation }
  # This should return the minimal set of attributes required to create a valid
  # Remediation. As you add validations to Remediation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { problems: [],
      spreadsheet: Rack::Test::UploadedFile.new("#{Rails.root}/spec/fixtures/spreadsheets/Valid_Flickr_sheet.xlsx", 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
     }
  }

  let(:invalid_attributes) {
    { problems: [] }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RemediationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all remediations as @remediations" do
      remediation = Remediation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:remediations)).to eq([remediation])
    end
  end

  describe "GET #show" do
    it "assigns the requested remediation as @remediation" do
      remediation = Remediation.create! valid_attributes
      get :show, {:id => remediation.to_param}, valid_session
      expect(assigns(:remediation)).to eq(remediation)
    end
  end

  describe "GET #new" do
    it "assigns a new remediation as @remediation" do
      get :new, {}, valid_session
      expect(assigns(:remediation)).to be_a_new(Remediation)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Remediation" do
        expect {
          post :create, {:remediation => valid_attributes}, valid_session
        }.to change(Remediation, :count).by(1)
      end

      it "assigns a newly created remediation as @remediation" do
        post :create, {:remediation => valid_attributes}, valid_session
        expect(assigns(:remediation)).to be_a(Remediation)
        expect(assigns(:remediation)).to be_persisted
      end

      it "redirects to the created remediation" do
        post :create, {:remediation => valid_attributes}, valid_session
        expect(response).to redirect_to(Remediation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved remediation as @remediation" do
        post :create, {:remediation => invalid_attributes}, valid_session
        expect(assigns(:remediation)).to be_a_new(Remediation)
      end

      it "re-renders the 'new' template" do
        post :create, {:remediation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

end
